// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var wm;
    wm = WordMaestro;
    return $('#pattern').change(function() {
      var html, matching_words, pattern, word;
      $('#spinner').show();
      pattern = $('#pattern').val();
      if ($('#scrambled').is(':checked')) {
        if (pattern.length > 8) {
          matching_words = ['Inte mer än 8 tecken med blandad sökning!'];
        } else {
          matching_words = wm.findPermutedAndShortendWord(pattern);
        }
      } else {
        matching_words = wm.findWord(pattern);
      }
      if (matching_words.length > 10) {
        matching_words = matching_words.slice(0, 10);
      }
      if (matching_words.length === 0) {
        matching_words = ['Inga träffar!'];
      }
      html = ((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = matching_words.length; _i < _len; _i++) {
          word = matching_words[_i];
          _results.push("<li>" + word + "</li>");
        }
        return _results;
      })()).join('\n');
      $('#matching-words').empty().html(html).listview('refresh');
      return $('#spinner').hide();
    });
  });

}).call(this);
