// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var capitalize, showMatches, worker;
    capitalize = function(word) {
      return word.charAt(0).toUpperCase() + word.slice(1);
    };
    showMatches = function(matchingWords) {
      var html, word;
      if (matchingWords.length > 10) {
        matchingWords = matchingWords.slice(0, 10);
      }
      if (matchingWords.length === 0) {
        matchingWords = ['Inga träffar!'];
      }
      html = ((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = matchingWords.length; _i < _len; _i++) {
          word = matchingWords[_i];
          _results.push("<li>" + (capitalize(word)) + "</li>");
        }
        return _results;
      })()).join('\n');
      return $('#matching-words').empty().html(html).listview('refresh');
    };
    worker = new Worker('lib/worker.js');
    worker.addEventListener('message', function(e) {
      console.log(e.data);
      showMatches(e.data.matchingWords);
      $('#spinner').hide();
      return false;
    });
    return $('#pattern').change(function() {
      var pattern;
      pattern = $('#pattern').val();
      if ($('#scrambled').is(':checked')) {
        if (pattern.length > 8) {
          return showMatches(['Inte mer än 8 tecken med blandad sökning!']);
        } else {
          $('#spinner').show();
          return worker.postMessage({
            cmd: 'findPermutedAndShortendWord',
            pattern: pattern
          });
        }
      } else {
        $('#spinner').show();
        return worker.postMessage({
          cmd: 'findWord',
          pattern: pattern
        });
      }
    });
  });

}).call(this);
