// Generated by CoffeeScript 1.4.0
(function() {
  var capitalize, postMessage, search, showMatches, worker, workersSupported;

  worker = null;

  search = function() {
    var pattern;
    pattern = $('#pattern').val().toLowerCase();
    if ($('#scrambled').is(':checked')) {
      if (pattern.length > 8) {
        return showMatches(['Inte mer än 8 tecken med blandad sökning!']);
      } else {
        return postMessage('findPermutedAndShortendWord', pattern);
      }
    } else {
      return postMessage('findWord', pattern);
    }
  };

  showMatches = function(matchingWords) {
    var html, word;
    if (matchingWords.length > 10) {
      matchingWords = matchingWords.slice(0, 10);
    }
    if (matchingWords.length === 0) {
      matchingWords = ['Inga träffar!'];
    }
    html = ((function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = matchingWords.length; _i < _len; _i++) {
        word = matchingWords[_i];
        _results.push("<li>" + (capitalize(word)) + "</li>");
      }
      return _results;
    })()).join('\n');
    return $('#matching-words').empty().html(html).listview('refresh');
  };

  capitalize = function(word) {
    return word.charAt(0).toUpperCase() + word.slice(1);
  };

  postMessage = function(cmd, pattern) {
    $.mobile.showPageLoadingMsg();
    return worker.postMessage({
      cmd: cmd,
      pattern: pattern
    });
  };

  workersSupported = function() {
    return window.Worker;
  };

  this.mainTest = {
    capitalize: capitalize
  };

  $(function() {
    if (!workersSupported()) {
      window.location = './unsupported-browser.html';
    }
    worker = new Worker(window.workerFile);
    worker.addEventListener('message', function(e) {
      showMatches(e.data.matchingWords);
      return $.mobile.hidePageLoadingMsg();
    });
    $('#pattern').change(search);
    return $('#scrambled').click(search);
  });

}).call(this);
