// Generated by CoffeeScript 1.4.0
(function() {

  this.addMessageHandler = function(context, wm) {
    var messageHandler;
    messageHandler = function(e) {
      var matchingWords;
      matchingWords = [];
      if (e.data.cmd === 'findPermutedAndShortendWord') {
        matchingWords = wm.findPermutedAndShortendWord(e.data.pattern);
      } else {
        matchingWords = wm.findWord(e.data.pattern);
      }
      return context.postMessage({
        matchingWords: matchingWords
      });
    };
    return context.addEventListener('message', messageHandler);
  };

}).call(this);
