// Generated by CoffeeScript 1.4.0
(function() {

  this.addMessageHandler = function(context, delegate) {
    var messageHandler;
    messageHandler = function(e) {
      var matchingWords;
      matchingWords = delegate[e.data.cmd](e.data.pattern);
      return context.postMessage({
        matchingWords: matchingWords
      });
    };
    return context.addEventListener('message', messageHandler);
  };

}).call(this);
