// Generated by CoffeeScript 1.4.0
(function() {
  var messageHandler, wm;

  importScripts('../data/swedish-word-list.js', 'word-maestro.js');

  wm = this.WordMaestro;

  messageHandler = function(e) {
    var matchingWords;
    matchingWords = [];
    if (e.data.cmd === 'findPermutedAndShortendWord') {
      matchingWords = wm.findPermutedAndShortendWord(e.data.pattern);
    } else {
      matchingWords = wm.findWord(e.data.pattern);
    }
    return postMessage({
      matchingWords: matchingWords
    });
  };

  addEventListener('message', messageHandler);

}).call(this);
