// Generated by CoffeeScript 1.4.0
(function() {

  describe('main', function() {
    var main;
    main = window.mainTest;
    return describe('capitalize', function() {
      return it('capitalizes a word', function() {
        return expect(main.capitalize('elefant')).toEqual('Elefant');
      });
    });
  });

}).call(this);
